[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai_web_tester"
version = "0.1.0"
description = "AI Web Testing Tool"
dependencies = [
    "selenium>=4.0.0",
    "webdriver-manager>=3.8.0",
]
